name: 01 - Building Blocks

on: [ push ]

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Continue on error step
        continue-on-error: true
        run: |
          echo "I will fail but continue"
          exit 1
      - name: Say goodbye
        run: echo "Goodbye!"
